package com.github.Simon04090.AppliedExchange.core;

import java.util.Map;
import com.github.Simon04090.AppliedExchange.ModInfo;
import com.google.common.eventbus.EventBus;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.relauncher.IFMLLoadingPlugin;
import cpw.mods.fml.relauncher.IFMLLoadingPlugin.MCVersion;
import cpw.mods.fml.relauncher.IFMLLoadingPlugin.TransformerExclusions;

@MCVersion("1.7.10") @TransformerExclusions("com.github.Simon04090.AppliedExchange.core") public class AppliedExchangeCore extends DummyModContainer implements IFMLLoadingPlugin{

	private final ModMetadata modMetadata = new ModMetadata();

	public AppliedExchangeCore(){
		this.modMetadata.autogenerated = false;
		this.modMetadata.authorList.add("Simon04090");
		this.modMetadata.credits = "JonBams for giving me the idea of doing this.";
		this.modMetadata.modId = this.getModId();
		this.modMetadata.version = this.getVersion();
		this.modMetadata.name = this.getName();
		this.modMetadata.description = "Coremod required for the awesome features of this mod.";
	}

	@EventHandler
	public void load(FMLInitializationEvent e){

	}

	@Override
	public boolean registerBus(EventBus bus, LoadController controller){
		return true;
	}

	@Override
	public String[] getASMTransformerClass(){
		return new String[]{"com.github.Simon04090.AppliedExchange.core.AppliedExchangeClassTransformer"};
	}

	@Override
	public String getModContainerClass(){
		return "com.github.Simon04090.AppliedExchange.core.AppliedExchangeCore";
	}

	@Override
	public String getSetupClass(){
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void injectData(Map<String, Object> data){
		// TODO Auto-generated method stub

	}

	@Override
	public String getAccessTransformerClass(){
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ModMetadata getMetadata(){
		return this.modMetadata;
	}

	@Override
	public String getModId(){
		return "appliedexchange-core";
	}

	@Override
	public String getName(){
		return "Applied Exchange Core";
	}

	@Override
	public String getVersion(){
		return ModInfo.version;
	}

	@Override
	public String getDisplayVersion(){
		return this.getVersion();
	}

}
